[base]
root_dir = "/dp/"
data_dir = "/dp/data/hive_exchange/"
hdfs_path = "hdfs://master"

[[db]]
id = "dp"
driver_class = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://127.0.0.1:3306/test?local_infile=1&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8"
user = "hadoop"
password = "hadoop"
