[base]
root_dir = "/dp/"
data_dir = "/dp/data/"
hdfs_path = "hdfs://192.168.247.100:9000"

[[db]]
id = "dp"
driver_class = "com.mysql.cj.jdbc.Driver"
url = "jdbc:mysql://localhost:3306/test"
user = "test"
password = "test"

